task1 [Кондратенко Александра]
mipt-diht/mipt-latex-fall2018-tardis-forever pull request #1
Opened 2018-10-19 06:21 UTC by tardis-forever

task1, Александра Кондратенко

2018-10-19 18:37 UTC, AShepelevv requested changes

2018-10-19 18:37 UTC, AShepelevv commented on task1.tex
> +	}
Табуляция и отступы, конечно, хорошо. Но в большом тексте такой стиль будет занимать много места в исходном коде. Лично я бы предпочтем писать в одну строчку,

2018-10-19 18:37 UTC, AShepelevv commented on task1.tex
> +	\hspace*{15pt}{\Large\textrm{\textbf {Геометрия}}} \hfill {\Large\textrm{\textbf {Планиметрия}}}
Зачем делать `\textrm' лишний раз?

2018-10-19 18:37 UTC, AShepelevv commented on task1.tex
> +		a^2 = b^2 + c^2 - 2bc\cos\alpha,
Когда формулы будут большими, подобное: `2bc\cos\alpha`, будет нечитаемо. Не плохо ставить пробелы, например, `2 b c \cos\alpha`

2018-10-19 18:37 UTC, AShepelevv commented on task1.tex
> +		\mathrm{tg}\frac{\alpha}{2} = \sqrt{\frac{\left( p - b \right) \left( p - c \right)}{p \left( p - a \right)}}.
`\left( p - b \right)` тут `\left` и `\right` в принципе не обязательны, когда внутри скобок что-то простое, можно и обычными. Но это лишь заметка))

2018-10-19 18:37 UTC, AShepelevv commented on task1.tex
> +		\mathrm{tg}\frac{\alpha}{2} = \sqrt{\frac{\left( p - b \right) \left( p - c \right)}{p \left( p - a \right)}}.
А тангенс русский (`\tg`) не поддерживается по умолчанию?

2018-10-19 18:37 UTC, AShepelevv commented on task1.tex
> +	\cos\alpha = \frac{b^2 + c^2 - a^2}{2bc}.
Таб пропустила))

2018-10-19 18:37 UTC, AShepelevv commented
И куда тире из pdf делись?

2018-10-19 18:49 UTC, tardis-forever commented
> И куда тире из pdf делись?

измени масштаб страницы - они появятся (по крайней мере у меня так работает) - я не знаю, что это за артефакты

2018-10-19 18:50 UTC, tardis-forever commented on task1.tex
> +		\mathrm{tg}\frac{\alpha}{2} = \sqrt{\frac{\left( p - b \right) \left( p - c \right)}{p \left( p - a \right)}}.
нет, русский тангенс по умолчанию не поддерживается
можно, конечно \newcommand было сделать, но так было проще

2018-10-19 18:55 UTC, tardis-forever commented on task1.tex
> +	\cos\alpha = \frac{b^2 + c^2 - a^2}{2bc}.
какой таб?

2018-10-19 18:56 UTC, tardis-forever commented on task1.tex
> +		a^2 = b^2 + c^2 - 2bc\cos\alpha,
fixed

2018-10-19 18:56 UTC, tardis-forever commented on task1.tex
> +	\hspace*{15pt}{\Large\textrm{\textbf {Геометрия}}} \hfill {\Large\textrm{\textbf {Планиметрия}}}
fixed

2018-10-19 18:57 UTC, tardis-forever commented on task1.tex
> +	}
fixed

2018-10-20 06:39 UTC, AShepelevv requested changes

2018-10-20 06:39 UTC, AShepelevv commented on task1.tex
> +	\hspace*{15pt}{\Large\textrm{\textbf {Геометрия \hfill Планиметрия}}}
Все еще не понимаю, зачем тут нужен `\textrm`

2018-10-20 06:39 UTC, AShepelevv commented on task1.tex
> +		}
А чего тут в одну строчку тогда не написала? И `\\` лучше не отделять то предыдущего слова пробелом.

2018-10-20 06:39 UTC, AShepelevv commented on task1.tex
> +	\hspace*{15pt}{\Large\textrm{\textbf {Термодинамика}}}
Все еще не понимаю, зачем тут нужен `\textrm`.

2018-10-20 06:39 UTC, AShepelevv commented on task1.tex
> +	\cos\alpha = \frac{b^2 + c^2 - a^2}{2 b c}.
Нет таба

2018-10-20 06:50 UTC, tardis-forever commented on task1.tex
> +	\hspace*{15pt}{\Large\textrm{\textbf {Геометрия \hfill Планиметрия}}}
fixed

2018-10-20 06:50 UTC, tardis-forever commented on task1.tex
> +	\hspace*{15pt}{\Large\textrm{\textbf {Термодинамика}}}
fixed

2018-10-20 06:51 UTC, tardis-forever commented on task1.tex
> +		}
fixed

2018-10-20 06:51 UTC, AShepelevv requested changes

2018-10-20 06:51 UTC, AShepelevv commented on task1.tex
> +		\mathrm{tg}\frac{\alpha}{2} = \sqrt{\frac{\left( p - b \right) \left( p - c \right)}{p \left( p - a \right)}}.
По-русски тангенс пишется как `\tg`.

2018-10-20 06:52 UTC, tardis-forever commented on task1.tex
> +	\cos\alpha = \frac{b^2 + c^2 - a^2}{2 b c}.
fixed

2018-10-20 06:52 UTC, AShepelevv commented on task1.tex
> +		\mathrm{tg}\frac{\alpha}{2} = \sqrt{\frac{\left( p - b \right) \left( p - c \right)}{p \left( p - a \right)}}.
В смысле как оператор, в писать `\mathrm` для подобного – плохо.

2018-10-20 06:54 UTC, tardis-forever commented on task1.tex
> +		\mathrm{tg}\frac{\alpha}{2} = \sqrt{\frac{\left( p - b \right) \left( p - c \right)}{p \left( p - a \right)}}.
![image](https://user-images.githubusercontent.com/29913627/47252452-0dde2500-d44e-11e8-9fa0-472f598f3b33.png)

2018-10-20 06:55 UTC, tardis-forever commented on task1.tex
> +		\mathrm{tg}\frac{\alpha}{2} = \sqrt{\frac{\left( p - b \right) \left( p - c \right)}{p \left( p - a \right)}}.
этой команды нет по умолчанию

2018-10-20 06:58 UTC, tardis-forever commented on task1.tex
> +		\mathrm{tg}\frac{\alpha}{2} = \sqrt{\frac{\left( p - b \right) \left( p - c \right)}{p \left( p - a \right)}}.
https://tex.stackexchange.com/questions/289949/defining-tg-so-it-behaves-exactly-like-sin-and-cos - я уже писала, что обычно пишут \newcommand, но я не видела смысла в этом ради одного случая

2018-10-20 10:36 UTC, AShepelevv commented on task1.tex
> +		\mathrm{tg}\frac{\alpha}{2} = \sqrt{\frac{\left( p - b \right) \left( p - c \right)}{p \left( p - a \right)}}.
А, ок, скорее всего он есть в каких-нибудь пакетах, чтобы самому не определять, хотя мы уже на следующем занятии научимся это делать.

2018-10-20 10:37 UTC, merged